### ISSUE TITLE
Customizable set of file extension

### ISSUE THREAD

**Issue by AndreyAkinshin** [elenderg/Plain-English-Extension-for-VS-Code#1]
You extension is awesome, thanks for implementing this! I would love to use it with .md files, but the file extension list is hardcoded. Could you please introduce an setting so that it's possible to configure the file extensions?

**Comment by AndreyAkinshin** [comment]
Sorry for this issue. I thought that it support the general English grammar, not .pe only.

**Comment by roke-julian-lockhart** [comment]
> https://github.com/elenderg/Plain-English-Extension-for-VS-Code/issues/1#issuecomment-2219510028

@AndreyAkinshin, probably better to close as not planned.
